Repository StudyBuddyCorps/Front-end, pull requests merged in 2024-05, with the labels that each got.

#41 Feat: Setting 페이지 UI 구현(#11)
  src/assets/camera.png
  src/components/setting/Account.tsx
  src/components/setting/CharacterPreview.tsx
  src/components/setting/EditProfile.tsx
  src/components/setting/EnvCharacterList.tsx
  src/components/setting/EnvGPTType.tsx
  src/components/setting/EnvPhrase.tsx
  src/components/setting/EnvSetting.tsx
  src/components/setting/EvnRoomType.tsx
  src/components/setting/GoalSetting.tsx
  src/components/setting/OptionData.ts
  src/components/setting/SelectBox.tsx
  src/components/setting/Tab.tsx
  src/components/studySetting/Radio.tsx
  src/components/studySetting/StudyType.tsx
  src/pages/Home.tsx
  src/pages/Setting.tsx
Labels: UI

#46 Fix: Home 페이지 관련 ui 수정 (#45)
  src/pages/Home.tsx
  src/shared/Header.tsx
Labels: UI, FIX

#48 feat: 스터디 도우미 ui 구현 (#47)
  src/components/studySetting/DefaultSetting.tsx
  src/components/studySetting/StudyHelper.tsx
  src/components/studySetting/StudyMate.tsx
  src/pages/StudyRoomSetting.tsx
Labels: UI

#50 Feat: 비밀번호 변경 페이지 구현(#49)
  src/assets/rock.png
  src/pages/ResetPwd.tsx
  src/pages/index.js
  src/shared/Router.tsx
Labels: UI

#52 Refactor: 이미지 파일 이동 (#51)
  src/assets/images/Done.png
  src/assets/images/Img_box.png
  src/assets/images/Logo.png
  src/assets/images/Noti.png
  src/assets/images/Noti2.png
  src/assets/images/Switch.png
  src/assets/images/account.png
  src/assets/images/arrow_right.png
  src/assets/images/avatar_woman.png
  src/assets/images/btn_create.png
  src/assets/images/btn_entrance.png
  src/assets/images/camera.png
  src/assets/images/change_radio.png
  src/assets/images/date.png
  src/assets/images/flag.png
  src/assets/images/google.png
  src/assets/images/group.png
  src/assets/images/hideView.png
  src/assets/images/home.png
  src/assets/images/kakao.png
  src/assets/images/lock.png
  src/assets/images/main.png
  src/assets/images/message.png
  src/assets/images/next_icon.png
  src/assets/images/normal_radio.png
  src/assets/images/notHideView.png
  src/assets/images/play.png
  src/assets/images/prev_icon.png
  src/assets/images/profile.png
  src/assets/images/rock.png
  src/assets/images/setting.png
  src/assets/images/sound_boy.png
  src/assets/images/sound_man.png
  src/assets/images/sound_mute.png
  src/assets/images/sound_woman.png
  src/assets/images/unSwitch.png
  src/assets/images/upload.png
  src/components/account/Join.tsx
  src/components/account/Login.tsx
  src/components/calendar/MyHistoryCalendar.tsx
  src/components/group/GroupListItem.tsx
  src/components/setting/EditProfile.tsx
  src/components/setting/EnvCharacterList.tsx
  src/components/studySetting/CharacterList.tsx
  src/components/studySetting/DefaultSetting.tsx
  src/components/studySetting/Radio.tsx
  src/components/studySetting/StudyType.tsx
  src/components/studySetting/UploadImg.tsx
  src/components/studySetting/VoiceList.tsx
  src/pages/Account.tsx
  src/pages/Home.tsx
  src/pages/Main.tsx
  src/pages/ResetPwd.tsx
  src/pages/Setting.tsx
  src/shared/Sidebar.tsx
  src/shared/Time.tsx
Labels: REFACTOR

#56 Feat: 사용자 가이드라인 UI 구현 (#54)
  src/components/common/GuideLine.tsx
  src/components/studySetting/DefaultSetting.tsx
  src/pages/Home.tsx
  src/pages/StudyRoomSetting.tsx
Labels: UI, FIX

#58 Feat: 커스텀 모달 구현 (#57)
  public/index.html
  src/components/common/AlertModal.tsx
  src/components/common/ConfirmModal.tsx
  src/hooks/useAlert.ts
  src/hooks/useConfirm.ts
Labels: UI, FEAT

#59 feat: 로그아웃 모달 구현 (#53)
  src/pages/Home.tsx
Labels: UI

#60 Feat: 기본 스터디룸 ui 구현 (#8)
  src/assets/images/Finish.png
  src/assets/images/Headphones.png
  src/assets/images/Play_duotone.png
  src/assets/images/Stop.png
  src/components/common/GuideLine.tsx
  src/components/common/VideoPlayer.tsx
  src/components/studyRoom/Controls.tsx
  src/components/studyRoom/Feedback.tsx
  src/components/studyRoom/Pause.tsx
  src/components/studyRoom/Timer.tsx
  src/pages/StudyRoom.tsx
Labels: UI

#65 feat: Group page 및 member page 생성
  src/components/common/FieldStyle.tsx
  src/components/common/Layout/Footer.tsx
  src/components/common/Layout/MainLayout.tsx
  src/components/common/SearchField.tsx
  src/components/group/MemberField.tsx
  src/components/group/MemberProfile.tsx
  src/pages/Group.tsx
  src/pages/GroupMain.tsx
  src/pages/MemberCalendar.tsx
  src/shared/Header.tsx
Labels: UI, FEAT
